# Основные настройки Solana Token Deployer

# Настройки Solana
solana:
  network: "mainnet"  # mainnet, testnet, devnet
  rpc_url: "https://api.mainnet.solana.com"
  commitment: "confirmed"
  
# Настройки кошелька
wallet:
  keypair_path: "~/.config/solana/id.json"
  backup_path: "./wallets/backup/"
  
# Настройки токенов
token:
  default_decimals: 9
  default_supply: 1000000000  # 1 миллиард токенов
  metadata_uri_base: "https://your-domain.com/metadata/"
  
# Настройки DEX
dex:
  raydium:
    enabled: true
    program_id: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
    fee_rate: 0.0025  # 0.25%
  
  orca:
    enabled: true
    program_id: "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP"
    fee_rate: 0.003   # 0.3%
    
  jupiter:
    enabled: true
    api_url: "https://quote-api.jup.ag/v6"
    
# Настройки ликвидности
liquidity:
  initial_sol_amount: 10.0  # SOL для начальной ликвидности
  initial_token_ratio: 1000000  # Токенов на 1 SOL
  slippage_tolerance: 0.01  # 1%
  
# Настройки маркетинга
marketing:
  website:
    enabled: true
    template: "modern"
    domain_provider: "namecheap"
    
  social_media:
    twitter:
      enabled: true
      api_key: ""
      api_secret: ""
      access_token: ""
      access_token_secret: ""
      
    discord:
      enabled: true
      bot_token: ""
      
    telegram:
      enabled: true
      bot_token: ""
      channel_id: ""
      
# Настройки аналитики
analytics:
  price_check_interval: 60  # секунд
  holder_analysis_interval: 3600  # секунд
  report_generation_interval: 86400  # секунд (24 часа)
  
# Настройки логирования
logging:
  level: "INFO"
  file: "logs/solana_deployer.log"
  max_size: "10MB"
  backup_count: 5
  
# Настройки безопасности
security:
  max_tokens_per_day: 10
  min_sol_balance: 1.0
  enable_rate_limiting: true
  max_requests_per_minute: 60
