name: Build Solana BPF Program

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-bpf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.0/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install BPF tools
        run: sudo apt-get update && sudo apt-get install -y llvm clang pkg-config

      - name: Build Solana BPF program
        run: solana program build ./custom_write_program

      - name: Upload BPF artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom_write_program_bpf
          path: custom_write_program/target/deploy/custom_write_program.so

      - name: Setup Solana keypair
        run: |
          echo "${{ secrets.SOLANA_KEYPAIR }}" > /tmp/solana-keypair.json
          solana config set --keypair /tmp/solana-keypair.json
          solana config set --url ${{ secrets.SOLANA_RPC_URL }}

      - name: Deploy program to Solana
        run: |
          solana --version
          solana program deploy ./custom_write_program/target/deploy/custom_write_program.so

      - name: Build Solana BPF program
        run: |
          cargo build-bpf
        working-directory: ./custom_write_program

      - name: Upload BPF artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom_write_program_bpf
          path: custom_write_program/target/deploy/custom_write_program.so
